app:
  schema: autoscale_test
spring:
  quartz:
    properties:
      org:
        quartz:
          dataSource:
            pg:
              URL: jdbc:postgresql://localhost:5432/postgres?currentSchema=${app.schema}
              user: postgres
              password: postgres
